rename Sammlung_Allgemein.pdf ad_sammelmappe.pdf
rename Sammlung_Bauanleitungen.pdf af_sammelmappe.pdf
rename Sammlung_Binaerwuerfel.pdf abw_sammelmappe.pdf
rename Sammlung_Caesarscheibe.pdf ac_sammelmappe.pdf
rename Sammlung_Coding.pdf ap_sammelmappe.pdf
rename Sammlung_Forschung.pdf afs_sammelmappe.pdf
rename Sammlung_Geobrett.pdf ag_sammelmappe.pdf
rename Sammlung_Getriebe.pdf az_sammelmappe.pdf
rename Sammlung_Hanoi.pdf ah_sammelmappe.pdf
rename Sammlung_muehle.pdf am_sammelmappe.pdf
rename Sammlung_SOMA.pdf as_sammelmappe.pdf
rename Sammlung_Tangram.pdf at_sammelmappe.pdf
rename Sammlung_Tetris.pdf ae_sammelmappe.pdf
rename Sammlung_tictactoe.pdf att_sammelmappe.pdf
rename Sammlung_Wuerfelbrett.pdf aw_sammelmappe.pdf
rename Sammlung_Zauberquadrate.pdf aq_sammelmappe.pdf
rename Spiele_selber_machen.pdf asp_sammelmappe.pdf
rename Sammlung_tictactoe.pdf att_sammelmappe.pdf
pause